CREATE TABLE IF NOT EXISTS customer (
    id BIGINT AUTO_INCREMENT,
    identification_number VARCHAR(20) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    surname VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS contract (
    id BIGINT AUTO_INCREMENT,
    number VARCHAR(100) NOT NULL,
    price DOUBLE NOT NULL
);